sips:
	sips -s format png -o test_full.png test_full.svg
	sips -s format png -o test_full2.png test_full2.svg
	sips -s format png -o test_p1.png test_p1.svg
	sips -s format png -o test_p2.png test_p2.svg
	sips -s format png -o test_resources.png test_resources.svg
	sips -s format png -o test_weekly.png test_weekly.svg
	sips -s format png -o test.png test.svg


sipsjpg:
	sips -s format jpg -o test_full.jpg test_full.svg
	sips -s format jpg -o test_full2.jpg test_full2.svg
	sips -s format jpg -o test_p1.jpg test_p1.svg
	sips -s format jpg -o test_p2.jpg test_p2.svg
	sips -s format jpg -o test_resources.jpg test_resources.svg
	sips -s format jpg -o test_weekly.jpg test_weekly.svg
	sips -s format jpg -o test.jpg test.svg
